# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Desktop/EE2026Lab/audio_effects_final_draft1/audio_effects.cache/wt [current_project]
set_property parent.project_path D:/Desktop/EE2026Lab/audio_effects_final_draft1/audio_effects.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  D:/Desktop/EE2026Lab/audio_effects_final_draft1/audio_effects.srcs/sources_1/new/slowclock.v
  D:/Desktop/EE2026Lab/audio_effects_final_draft1/audio_effects.srcs/sources_1/new/delay_mic.v
  D:/Desktop/EE2026Lab/audio_effects_final_draft1/audio_effects.srcs/sources_1/new/SPI.v
  D:/Desktop/EE2026Lab/audio_effects_final_draft1/audio_effects.srcs/sources_1/new/AUDIO_FX_TOP.v
  D:/Desktop/EE2026Lab/audio_effects_final_draft1/audio_effects.srcs/sources_1/new/record_and_play.v
  D:/Desktop/EE2026Lab/audio_effects_final_draft1/audio_effects.srcs/sources_1/new/manual_counter.v
  D:/Desktop/EE2026Lab/audio_effects_final_draft1/audio_effects.srcs/sources_1/new/dff.v
  D:/Desktop/EE2026Lab/audio_effects_final_draft1/audio_effects.srcs/sources_1/new/single_pulse.v
  D:/Desktop/EE2026Lab/audio_effects_final_draft1/audio_effects.srcs/sources_1/new/seven_segment.v
  D:/Desktop/EE2026Lab/audio_effects_final_draft1/audio_effects.srcs/sources_1/new/pitch_delay_clock.v
  D:/Desktop/EE2026Lab/audio_effects_final_draft1/audio_effects.srcs/sources_1/new/pitch_shift_realtime.v
  D:/Desktop/EE2026Lab/audio_effects_final_draft1/audio_effects.srcs/sources_1/new/delay_mic_new.v
  D:/Desktop/EE2026Lab/audio_effects_final_draft1/audio_effects.srcs/sources_1/new/pitch_shift_realtime_v3.v
  D:/Desktop/EE2026Lab/audio_effects_final_draft1/audio_effects.srcs/sources_1/new/sound_merge.v
  D:/Desktop/EE2026Lab/audio_effects_final_draft1/audio_effects.srcs/sources_1/new/instruments.v
  D:/Desktop/EE2026Lab/audio_effects_final_draft1/audio_effects.srcs/sources_1/new/pitch_shift_realtime_v2.v
  D:/Desktop/EE2026Lab/audio_effects_final_draft1/audio_effects.srcs/sources_1/new/pitch_delay_clk_v2.v
  D:/Desktop/EE2026Lab/audio_effects_final_draft1/audio_effects.srcs/sources_1/new/song_player.v
  D:/Desktop/EE2026Lab/audio_effects_final_draft1/audio_effects.srcs/sources_1/new/test_bits.v
}
read_vhdl -library xil_defaultlib D:/Desktop/EE2026Lab/audio_effects_final_draft1/audio_effects.srcs/sources_1/imports/audio_effects.srcs/DA2CompRef.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Desktop/EE2026Lab/audio_effects_final_draft1/audio_effects.srcs/constrs_1/imports/Learn/Basys3_Master.xdc
set_property used_in_implementation false [get_files D:/Desktop/EE2026Lab/audio_effects_final_draft1/audio_effects.srcs/constrs_1/imports/Learn/Basys3_Master.xdc]


synth_design -top AUDIO_FX_TOP -part xc7a35tcpg236-1 -flatten_hierarchy none -directive RuntimeOptimized -fsm_extraction off


write_checkpoint -force -noxdef AUDIO_FX_TOP.dcp

catch { report_utilization -file AUDIO_FX_TOP_utilization_synth.rpt -pb AUDIO_FX_TOP_utilization_synth.pb }
